site_name: Helpop Plugin
site_description: HelpopPlugin is a TShock plugin that enables cross-server reports or calls for help.
site_author: Arthri
site_url: https://arthri.github.io/HelpopPlugin
repo_url: https://github.com/Arthri/HelpopPlugin
copyright: Copyright © Arthri 2022

plugins:
  search: {}
  minify:
    minify_html: true
  macros:
    module_name: 'docs/main'

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: slate
      primary: amber
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Arthri/HelpopPlugin

nav:
  - Home:
    - Index: 'index.md'
    - Installation: 'installation.md'
    - Usage: 'usage.md'
    - Development: 'development.md'
    - License: 'LICENSE.md'
    - Acknowledgements: 'Acknowledgements.md'
  - Configuration:
    - Index: 'Configuration/index.md'
    - General: 'Configuration/General.md'
    - Redis: 'Configuration/Redis.md'
    - Report Template: 'Configuration/Report_Template.md'
  - Commands:
    - Issues: 'Commands/Reports.md'
    - Maintenance: 'Commands/Maintenance.md'
    - Uncategorized: 'Commands/Uncategorized.md'

markdown_extensions:
  attr_list: {}
  footnotes: {}
  admonition: {}
  pymdownx.details: {}
  pymdownx.highlight: {}
  pymdownx.inlinehilite: {}
  pymdownx.magiclink: {}
  pymdownx.saneheaders: {}
  pymdownx.smartsymbols: {}
  pymdownx.superfences: {}
  pymdownx.snippets:
      check_paths: true
  toc:
    permalink: true
